# Generated by Django 3.0.7 on 2020-06-19 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
    ]
