# Generated by Django 3.0.7 on 2020-06-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_memberbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberbook',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
